In [6]:
from zipfile import ZipFile
import pandas as pd

In [25]:
data_path='../files/input/train_data.csv.zip'
test_path='../files/input/test_data.csv.zip'

In [1]:
print('Hola mundo')

Hola mundo


In [26]:
# Load the CSV file in the zip file and store it in a DataFrame
with ZipFile(data_path) as z:
    with z.open('train_default_of_credit_card_clients.csv') as f:
        data=pd.read_csv(f)
with ZipFile(test_path) as z:
    with z.open('test_default_of_credit_card_clients.csv') as f:
        test=pd.read_csv(f)

In [10]:
data.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0  10748     310000    1          3         1   32      0      0      0   
1  12574      10000    2          3         1   49     -1     -1     -2   
2  29677      50000    1          2         1   28     -1     -1     -1   
3   8857      80000    2          3         1   52      2      2      3   
4  21099     270000    1          1         2   34      1      2      0   

   PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0      0  ...      84373      57779      14163      8295      6000      4000   
1     -1  ...       1690       1138        930         0         0      2828   
2      0  ...      45975       1300      43987         0     46257      2200   
3      3  ...      40748      39816      40607      3700      1600      1600   
4      0  ...      22448      15490      17343         0      4000      2000   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0      3000      1000      2000                           0  
1         0       182         0                           1  
2      1300     43987      1386                           0  
3         0      1600      1600                           1  
4         0      2000      2000                           0  

[5 rows x 25 columns]

In [15]:
data['PAY_3'].value_counts()

PAY_3
 0    11082
-1     4136
-2     2853
 2     2664
 3      161
 4       53
 6       17
 7       14
 5       13
 1        4
 8        3
Name: count, dtype: int64

In [14]:
data['PAY_0'].value_counts()

PAY_0
 0    10358
-1     3951
 1     2622
-2     1891
 2     1863
 3      219
 4       48
 5       17
 8       15
 6       10
 7        6
Name: count, dtype: int64

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21000 entries, 0 to 20999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          21000 non-null  int64
 1   LIMIT_BAL                   21000 non-null  int64
 2   SEX                         21000 non-null  int64
 3   EDUCATION                   21000 non-null  int64
 4   MARRIAGE                    21000 non-null  int64
 5   AGE                         21000 non-null  int64
 6   PAY_0                       21000 non-null  int64
 7   PAY_2                       21000 non-null  int64
 8   PAY_3                       21000 non-null  int64
 9   PAY_4                       21000 non-null  int64
 10  PAY_5                       21000 non-null  int64
 11  PAY_6                       21000 non-null  int64
 12  BILL_AMT1                   21000 non-null  int64
 13  BILL_AMT2                   21000 non-null  int64
 14  BILL_A

In [20]:
data_not_null=data.dropna()

In [21]:
data_not_null.shape

(21000, 25)

In [19]:
data.isna().sum()

ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default payment next month    0
dtype: int64

In [47]:
clean_train_data = pd.read_csv('../train_data_clean.csv')

In [48]:
clean_train_data.shape

(20953, 24)

In [49]:
clean_train_data['EDUCATION'].value_counts()

EDUCATION
2.0    9756
1.0    7476
3.0    3396
4.0     325
Name: count, dtype: int64

In [52]:
clean_train_data.describe()

LIMIT_BAL           AGE     BILL_AMT1      BILL_AMT2     BILL_AMT3  \
count    20953.00000  20953.000000   20953.00000   20953.000000  2.095300e+04   
mean    167245.35866     35.485515   51630.41574   49593.252708  4.739277e+04   
std     129698.73226      9.253303   74070.13405   71592.435795  7.007749e+04   
min      10000.00000     21.000000 -165580.00000  -69777.000000 -1.572640e+05   
25%      50000.00000     28.000000    3645.00000    3058.000000  2.779000e+03   
50%     140000.00000     34.000000   22582.00000   21338.000000  2.023700e+04   
75%     240000.00000     41.000000   67519.00000   64653.000000  6.021000e+04   
max    1000000.00000     79.000000  964511.00000  983931.000000  1.664089e+06   

           BILL_AMT4      BILL_AMT5      BILL_AMT6       PAY_AMT1  \
count   20953.000000   20953.000000   20953.000000   20953.000000   
mean    43576.966878   40721.500262   39354.690355    5729.808428   
std     64846.521522   61292.851909   60174.607281   17158.838834   
min    -81334.000000  -81334.000000 -339603.000000       0.000000   
25%      2400.000000    1770.000000    1261.000000    1000.000000   
50%     19087.000000   18238.000000   17263.000000    2108.000000   
75%     54574.000000   50340.000000   49525.000000    5004.000000   
max    891586.000000  927171.000000  961664.000000  873552.000000   

           PAY_AMT2       PAY_AMT3       PAY_AMT4       PAY_AMT5  \
count  2.095300e+04   20953.000000   20953.000000   20953.000000   
mean   5.843411e+03    5208.908987    4902.974085    4876.495824   
std    2.309554e+04   18086.675162   15981.996029   15454.418396   
min    0.000000e+00       0.000000       0.000000       0.000000   
25%    8.460000e+02     390.000000     284.000000     249.000000   
50%    2.014000e+03    1826.000000    1500.000000    1500.000000   
75%    5.000000e+03    4564.000000    4077.000000    4079.000000   
max    1.684259e+06  896040.000000  621000.000000  426529.000000   

            PAY_AMT6       default  
count   20953.000000  20953.000000  
mean     5266.683100      0.225505  
std     18315.425134      0.417924  
min         0.000000      0.000000  
25%        91.000000      0.000000  
50%      1500.000000      0.000000  
75%      4000.000000      0.000000  
max    528666.000000      1.000000

In [51]:
# Reclasificar las variables PAY_i, EDUCATION, SEX y MARRIAGE a categoricas
cat_columns = ['PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'EDUCATION', 'SEX', 'MARRIAGE']
for col in cat_columns:
    clean_train_data[col] = clean_train_data[col].astype('category')

In [43]:
X=clean_train_data.drop('default', axis=1)

In [36]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

In [53]:
# Aplicar OneHotEncoder a las variables categóricas
enc=OneHotEncoder()

In [54]:
enc.fit(X)

OneHotEncoder()

In [55]:
enc.categories_

[array([  10000,   16000,   20000,   30000,   40000,   50000,   60000,
          70000,   80000,   90000,  100000,  110000,  120000,  130000,
         140000,  150000,  160000,  170000,  180000,  190000,  200000,
         210000,  220000,  230000,  240000,  250000,  260000,  270000,
         280000,  290000,  300000,  310000,  320000,  330000,  340000,
         350000,  360000,  370000,  380000,  390000,  400000,  410000,
         420000,  430000,  440000,  450000,  460000,  470000,  480000,
         490000,  500000,  510000,  520000,  530000,  540000,  550000,
         560000,  570000,  580000,  590000,  600000,  610000,  620000,
         630000,  640000,  650000,  660000,  670000,  680000,  690000,
         700000,  710000,  720000,  730000,  740000,  750000,  760000,
         780000,  800000, 1000000]),
 array([1, 2]),
 array([1., 2., 3., 4.]),
 array([1., 2., 3.]),
 array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
        38, 39, 40, 41, 42, 43, 44, 45, 46

In [27]:
test.shape

(9000, 25)